### ISSUE TITLE
testrig parsing: iptables parse error not reported on error log

### ISSUE THREAD

**Issue by virtuald** [batfish/batfish#233]
You have to enable debug logging to see the error. Here's what I see without debug logging enabled:

```
batfish> init-testrig test_rigs/test
Uploaded testrig. Parsing now.
Status: FAILURE
org.batfish.common.BatfishException: Batfish job failed
   at org.batfish.main.Driver$1.run(Driver.java:406)
Caused by: org.batfish.common.BatfishException: Key not found for iptables: testrig/iptables/n7.v4
   at org.batfish.main.Batfish.serializeHostConfigs(Batfish.java:4123)
   at org.batfish.main.Batfish.serializeVendorConfigs(Batfish.java:4298)
   at org.batfish.main.Batfish.run(Batfish.java:3926)
   at org.batfish.main.Driver$1.run(Driver.java:374)
```

When I enable debug logging via `set-loglevel debug`, I get a nice error message informing me that testrig/iptables/n7.v4 is broken. 

```
...
Error context lines:
   1:      # This is in iptables-save format
   2:      # @see http://www.faqs.org/docs/iptables/iptables-save.html
   3:      *filter
   4:      :INPUT DROP [0:0]
   5:      :FORWARD DROP [0:0]
>>>6:      -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
   7:      COMMIT
```

**Comment by ratulm** [comment]
@wenfei-wu - did you fix this issue recently? do you mind taking a look?

**Comment by kidsbear** [comment]
@ratulm I think it is a different issue because of inconsistency - for other parsing errors, we store the error information in AnswerElements instead of crash (except haltonprocesserror is set to true). However, current code throws an Exception for this error - https://github.com/batfish/batfish/blob/master/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L4125. I am trying to fix it, but I don't have a good idea in mind now. Any suggestions if you have time?

**Comment by ratulm** [comment]
@arifogel should be able to help here.

**Comment by ratulm** [comment]
addressed by 361b44ce189fa9d759cb30d2976d20813cfadb09

**Comment by virtuald** [comment]
Ok, so the output is better, as my sample testrig gives the following:

```
Init'ed and set active container
Uploaded testrig. Parsing now.
Status: SUCCESS
PARSING SUMMARY
  h1.iptables: failed to parse
STATISTICS
  Parsing results:
    Parsed successfully: 1
    Failed to parse: 1
```
But it still doesn't tell me *why* it failed to parse, whereas I can see that with debug info. Particularly with large configuration sets, re-running the testrig could take awhile when I could have just found out when I ran it the first time.

Looking a bit further, it appears that there is a `containers` directory with a logfile that contains the error information. It seems like it would be a good idea to output a message saying "See /path/to/logfile for more details" (or something similar) that way the (new/uninformed user) knows where to look instead of needing to run again.

**Comment by arifogel** [comment]
Did you try 'get initinfo verboseError=true' following initialization (if i
have that flag wrong, please see InitInfoQuestionPlugin.java)?

**Comment by virtuald** [comment]
That does show the desired output.

From a discoverability point of view, it would be nice if the user could be notified that they could do that. However, if you're running in batch mode, then the above problem still applies -- so it would be good to know about the logfile too.
